[package]
name = "musicdb-client"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
musicdb-lib = { path = "../musicdb-lib", default-features = false }
clap = { version = "4.5.45", features = ["derive"] }
directories = "6.0.0"
regex = "1.11.1"
speedy2d = { version = "2.1.0", optional = true }
toml = "0.9.5"
# musicdb-mers = { version = "0.1.0", path = "../musicdb-mers", optional = true }
uianimator = "0.1.1"

[features]
default = ["gui", "default-playback"]
# gui:
#   enables the gui modes
# merscfg:
#   allows using mers to configure the gui
# mers:
#   enables the run-mers mode
# playback:
#   enables syncplayer modes, where the client mirrors the server's playback
gui = ["speedy2d"]
# merscfg = ["mers", "gui"]
merscfg = []
# mers = ["musicdb-mers"]
mers = []
playback = []
default-playback = ["playback", "musicdb-lib/default-playback"]
playback-via-sleep = ["playback", "musicdb-lib/playback-via-sleep"]
playback-via-mpv = ["playback", "musicdb-lib/playback-via-mpv"]
playback-via-playback-rs = ["playback", "musicdb-lib/playback-via-playback-rs"]
playback-via-rodio = ["playback", "musicdb-lib/playback-via-rodio"]
